name: nessai-environment
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - scipy>=0.16
  - matplotlib
  - seaborn
  - tqdm
  - pytorch>=1.11.0
  - cpuonly
  - nessai>=0.7.0
  - corner
  - nbgitpuller
  - bilby
  - astropy>=5
  - lalsuite
  - gwpy
  - pytables
  - pyfftw
